-- MCP tool call tracing schema
-- Run this SQL against your Lakebase Postgres database to create the
-- tracing tables:
--   * agent_sessions: one row per agent/MCP session. The unique session ID
--     (UUID) is generated by Postgres itself via gen_random_uuid() whenever
--     a row is inserted without an explicit session_id, or reused from the
--     client's mcp-session-id header.
--   * mcp_traces: one row per MCP tool call, keyed to its session.

CREATE TABLE IF NOT EXISTS agent_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_email VARCHAR(255),
    source VARCHAR(50) NOT NULL DEFAULT 'generated',
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_activity_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    tool_call_count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mcp_traces (
    id SERIAL PRIMARY KEY,
    trace_id UUID UNIQUE DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES agent_sessions(session_id),
    tool_name VARCHAR(255) NOT NULL,
    arguments JSONB,
    result JSONB,
    user_email VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'success',
    duration_ms INTEGER,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_traces_trace_id ON mcp_traces(trace_id);
CREATE INDEX IF NOT EXISTS idx_traces_session_id ON mcp_traces(session_id);
CREATE INDEX IF NOT EXISTS idx_traces_tool_name ON mcp_traces(tool_name);
CREATE INDEX IF NOT EXISTS idx_traces_user_email ON mcp_traces(user_email);
CREATE INDEX IF NOT EXISTS idx_traces_created_at ON mcp_traces(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_user_email ON agent_sessions(user_email);
CREATE INDEX IF NOT EXISTS idx_sessions_started_at ON agent_sessions(started_at DESC);

-- Handy session-level view: every session with its trace summary
CREATE OR REPLACE VIEW v_session_traces AS
SELECT
    s.session_id,
    s.user_email,
    s.source,
    s.started_at,
    s.last_activity_at,
    s.tool_call_count,
    COUNT(t.id) AS traced_calls,
    COUNT(t.id) FILTER (WHERE t.status = 'error') AS errors,
    COALESCE(AVG(t.duration_ms), 0) AS avg_duration_ms
FROM agent_sessions s
LEFT JOIN mcp_traces t ON t.session_id = s.session_id
GROUP BY s.session_id, s.user_email, s.source, s.started_at, s.last_activity_at, s.tool_call_count;
